FROM python:3.9.7-alpine3.13

LABEL org.opencontainers.image.source = "https://github.com/neuro-inc/neuro-extras"

ENV LANG C.UTF-8
ENV PYTHONUNBUFFERED 1

ARG CLOUD_SDK_VERSION=347.0.0
ENV CLOUD_SDK_VERSION=$CLOUD_SDK_VERSION

RUN echo sdk=$CLOUD_SDK_VERSION