name: Tests

on:
  workflow_call: {}

permissions:
  contents: read

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout commit
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version-file: .python-version
          cache: pip
          cache-dependency-path: requirements/*.txt

      - name: Cache pre-commit hooks
        uses: actions/cache@v6
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-python-3.14-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install dependencies
        run: |
          make setup-ci

      - name: Run linters
        run: |
          make lint

  pretest:
    name: Prepare for tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      PYTHONIOENCODING: utf-8
      NEURO_STAGING_URL: "https://api.dev.apolo.us/api/v1"
      APOLO_TOKEN: ${{ secrets.CLIENT_TEST_E2E_USER_NAME }}
      APOLO_CLUSTER: default
      APOLO_PROJECT: apolo-extras
      APOLO_EXTRAS_PRESET: cpu-small
      # Note: ${{ github.sha }} not working, see https://github.com/actions/checkout/issues/299
      SHA: ${{ github.event.pull_request.head.sha || github.sha }}
    steps:
      - name: Checkout commit
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version-file: .python-version
          cache: pip
          cache-dependency-path: requirements/base.txt

      - name: Install and configure apolo
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/base.txt
          apolo config login-with-token ${{ env.APOLO_TOKEN }} ${{ env.NEURO_STAGING_URL }}
          apolo config switch-cluster ${{ env.APOLO_CLUSTER }}
          apolo config switch-project ${{ env.APOLO_PROJECT }}
          apolo --color=no config show

      - name: Login to ghcr.io
        uses: docker/login-action@v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build test image
        run: |
          export REPO_URL=https://github.com/neuro-inc/apolo-extras.git
          export PACKAGE="git+$REPO_URL@$SHA"
          docker build -t ghcr.io/neuro-inc/apolo-extras:$SHA \
            --build-arg APOLO_EXTRAS_PACKAGE=$PACKAGE .

      - name: Push test image
        run: |
          docker push ghcr.io/neuro-inc/apolo-extras:$SHA

      - name: Prepare volumes and disks
        shell: bash
        run: |
          make prepare-e2e-test

  test:
    name: Run tests
    needs: [pretest]
    strategy:
      fail-fast: false
      max-parallel: 3 # to avoid overloading the platform
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu, macos, windows]
        exclude:
          # not to overload the platform, we will remove this eventually
          # see https://github.com/neuro-inc/apolo-extras/pull/249
          - python-version: "3.12"
            os: macos
          - python-version: "3.12"
            os: windows
          - python-version: "3.13"
            os: macos
          - python-version: "3.13"
            os: windows
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 90
    env:
      PYTHONIOENCODING: utf-8
      AWS_APOLO_EXTRAS_TEST_USER_KEY_ID: ${{ secrets.AWS_APOLO_EXTRAS_TEST_USER_KEY_ID }}
      AWS_APOLO_EXTRAS_TEST_USER_ACCESS_KEY: ${{ secrets.AWS_APOLO_EXTRAS_TEST_USER_ACCESS_KEY }}
      APOLO_TOKEN: ${{ secrets.CLIENT_TEST_E2E_USER_NAME }}
      # AZURE_SAS_TOKEN: ${{ secrets.AZURE_SAS_TOKEN }}
      DOCKERHUB_CI_USERNAME: ${{ secrets.DOCKERHUB_CI_USERNAME }}
      DOCKERHUB_CI_TOKEN: ${{ secrets.DOCKERHUB_CI_TOKEN }}

    steps:
      - name: Checkout commit
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      # - name: Authorize GCP
      #   uses: google-github-actions/auth@v2
      #   with:
      #     credentials_json: ${{ secrets.E2E_TESTS_GCP_KEY }} # e2e-tests@development-421920.iam.gserviceaccount.com
      # GCP test are disabled since we cannot easily test it via internal network

      # - name: Setup gcloud
      #   uses: google-github-actions/setup-gcloud@v2

      - name: Configure AWS access
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ env.AWS_APOLO_EXTRAS_TEST_USER_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_APOLO_EXTRAS_TEST_USER_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            requirements/*.txt

      - name: Install rclone on Linux and macOS
        if: (matrix.os == 'ubuntu') || (matrix.os == 'macos')
        shell: bash
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Install libraries on Windows
        if: matrix.os == 'windows'
        run: choco install rclone --yes --no-progress

      - name: Install python dependencies
        run: |
          make setup-ci

      - name: Configure environment
        env:
          NEURO_STAGING_URL: "https://api.dev.apolo.us/api/v1"
          APOLO_TOKEN: ${{ env.APOLO_TOKEN }}
          APOLO_CLUSTER: default
          APOLO_PROJECT: apolo-extras
          APOLO_EXTRAS_PRESET: cpu-small
        run: |
          apolo config login-with-token ${{ env.APOLO_TOKEN }} ${{ env.NEURO_STAGING_URL }}
          apolo config switch-cluster ${{ env.APOLO_CLUSTER }}
          apolo config switch-project ${{ env.APOLO_PROJECT }}
          apolo --color=no config show
      - name: Read PR labels
        if: github.event_name == 'pull_request'
        uses: joerick/pr-labels-action@v1.0.9
        id: pr_labels

      - name: Run all tests
        if: |
          github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          COLOR: "yes"
          DOCKER_CI_USERNAME: ${{ env.DOCKERHUB_CI_USERNAME }}
          DOCKER_CI_TOKEN: ${{ env.DOCKERHUB_CI_TOKEN }}
          APOLO_CLUSTER: default
          #APOLO_CLUSTER_SECONDARY: cato-poc
          # AZURE_SAS_TOKEN: ${{ env.AZURE_SAS_TOKEN }}
          # Note: ${{ github.sha }} not working, see https://github.com/actions/checkout/issues/299
          SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          # Note: see tests/e2e/conftest.py:get_tested_archive_types()
          PYTEST_DATA_COPY_ARCHIVE_TYPES: ".tar.gz"
          PYTEST_PARALLEL: 6
        shell: bash
        run: |
          export APOLO_EXTRAS_IMAGE=ghcr.io/neuro-inc/apolo-extras:$SHA
          make test
      - name: Run smoke tests
        if: |
          github.event_name == 'pull_request'
        env:
          COLOR: "yes"
          DOCKER_CI_USERNAME: ${{ env.DOCKERHUB_CI_USERNAME }}
          DOCKER_CI_TOKEN: ${{ env.DOCKERHUB_CI_TOKEN }}
          APOLO_CLUSTER: default
          APOLO_EXTRAS_PRESET: cpu-small
          #APOLO_CLUSTER_SECONDARY: cato-poc
          # AZURE_SAS_TOKEN: ${{ env.AZURE_SAS_TOKEN }}
          # Note: ${{ github.sha }} not working, see https://github.com/actions/checkout/issues/299
          SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          # Note: see tests/e2e/conftest.py:get_tested_archive_types()
          PYTEST_DATA_COPY_ARCHIVE_TYPES: ".tar.gz"
          PYTEST_PARALLEL: 6
        shell: bash
        run: |
          export APOLO_EXTRAS_IMAGE=ghcr.io/neuro-inc/apolo-extras:$SHA
          make test_smoke
      - name: Run data tests
        if: |
          github.event_name == 'pull_request' &&
          contains(steps.pr_labels.outputs.labels, ' e2e-data ')
        env:
          COLOR: "yes"
          DOCKER_CI_USERNAME: ${{ env.DOCKERHUB_CI_USERNAME }}
          DOCKER_CI_TOKEN: ${{ env.DOCKERHUB_CI_TOKEN }}
          APOLO_CLUSTER: default
          #APOLO_CLUSTER_SECONDARY: cato-poc
          # AZURE_SAS_TOKEN: ${{ env.AZURE_SAS_TOKEN }}
          # Note: ${{ github.sha }} not working, see https://github.com/actions/checkout/issues/299
          SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          # Note: see tests/e2e/conftest.py:get_tested_archive_types()
          PYTEST_DATA_COPY_ARCHIVE_TYPES: ".tar.gz"
          PYTEST_PARALLEL: 6
        shell: bash
        run: |
          export APOLO_EXTRAS_IMAGE=ghcr.io/neuro-inc/apolo-extras:$SHA
          make test_data

      - name: Run image tests
        if: |
          github.event_name == 'pull_request' &&
          contains(steps.pr_labels.outputs.labels, ' e2e-image ')
        env:
          COLOR: "yes"
          DOCKER_CI_USERNAME: ${{ env.DOCKERHUB_CI_USERNAME }}
          DOCKER_CI_TOKEN: ${{ env.DOCKERHUB_CI_TOKEN }}
          APOLO_CLUSTER: default
          APOLO_EXTRAS_PRESET: cpu-small
          #APOLO_CLUSTER_SECONDARY: cato-poc
          # AZURE_SAS_TOKEN: ${{ env.AZURE_SAS_TOKEN }}
          # Note: ${{ github.sha }} not working, see https://github.com/actions/checkout/issues/299
          SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          # Note: see tests/e2e/conftest.py:get_tested_archive_types()
          PYTEST_DATA_COPY_ARCHIVE_TYPES: ".tar.gz"
          PYTEST_PARALLEL: auto
        shell: bash
        run: |
          export APOLO_EXTRAS_IMAGE=ghcr.io/neuro-inc/apolo-extras:$SHA
          make test_image

  check:
    name: Check
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
